name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: env
    permissions:
      contents: write
    steps:
      - name: basic
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.basic.svg
          config_timezone: Asia/Shanghai
          user: XieJiSS
          base: header, repositories
      - name: achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.achievements.svg
          user: XieJiSS
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
      - name: calendar and rss
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.calendar_rss.svg
          user: XieJiSS
          base: ""
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_rss: yes
          plugin_rss_source: http://blog.jiejiss.com/atom.xml
          plugin_rss_limit: 3
          config_order: isocalendar, rss
      - name: recent-language
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.recent_language.svg
          user: XieJiSS
          base: ""
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 180
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 7
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          commits_authoring: c141028@gmail.com, immellonji@yandex.com, 24671280+XieJiSS@users.noreply.github.com, XieJiSS@users.noreply.github.com
